// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section data-scroll="load" class="section-spacing-bottom"><div class="step-info"><div class="container"><div class="step-detail"><div class="step-caption"><div scroll-item=""><div class="pre-title w-variant-7e8276b8-3fa3-b83e-411c-2eeab6ce4110">How it works</div></div><h2 scroll-item="" class="step-title">Real people behind every repair.</h2></div><div class="w-layout-grid grid-step-list"><div scroll-item=""><div class="step-item w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number-badge"><div class="step-number-round w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number">01</div></div></div><div class="step-content w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><h3 class="heading-h5 no-margin-bottom">Transparency</h3><div>We quote before we touch. No extras added without your approval. The price we give is the price you pay.</div></div></div></div><div scroll-item=""><div class="step-item w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number-badge"><div class="step-number-round w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number">02</div></div></div><div class="step-content w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><h3 class="heading-h5 no-margin-bottom">Genuine parts</h3><div>We fit manufacturer-grade or OE-quality parts on every job. Cheap alternatives cost more in the long run.</div></div></div></div><div scroll-item=""><div class="step-item w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number-badge"><div class="step-number-round w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><div class="step-number">03</div></div></div><div class="step-content w-variant-5b6942ad-bdd1-213a-7e52-ab3f0f9d119c"><h3 class="heading-h5 no-margin-bottom">Clear communication</h3><div>We explain what's wrong in plain English, with no jargon, no upselling, and no vague "we recommend" lists.</div></div></div></div></div></div></div></div></section>`;

export default function AboutPageProcessSection() {
  return <ScrapedSection html={SECTION_HTML} qa="about-04-process" />;
}
