// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section data-scroll="load" class="section-spacing"><div class="container"><div class="w-layout-grid grid-story"><div class="story-left"><div class="story-content"><div scroll-item="" class="story-heading"><div class="pre-title w-variant-7e8276b8-3fa3-b83e-411c-2eeab6ce4110">Our Story</div><h2 class="story-title">The right repair, the first time.</h2></div><p scroll-item="" class="no-margin-bottom">After seeing drivers overcharged and confused for years, we built a workshop focused on honest service, quality workmanship, and complete transparency.</p><div scroll-item=""><a href="/services" class="button-primary w-variant-66141dc8-12be-af3f-9039-776e66b77489 w-inline-block"><div class="button-title">View services</div><div class="button-hover-bg"></div></a></div></div><div class="w-layout-grid grid-story-feature"><div scroll-item="" class="story-feature-item"><div class="story-feature-badge"><img loading="lazy" src="/images/pages/about/6a7437a66edcdf3e9d81fc4d_tag_1.svg" alt="Icon" class="story-feature-icon"></div><div class="story-feature-content"><div class="text-black">Fixed-price quotes before every repair</div></div></div><div scroll-item="" class="story-feature-item"><div class="story-feature-badge"><img loading="lazy" src="/images/pages/about/6a75b82c799955559326f271_loupe_3.svg" alt="Icon" class="story-feature-icon"></div><div class="story-feature-content"><div class="text-black">Diagnostics without dealership costs</div></div></div><div><div scroll-item="" class="story-feature-item"><div class="story-feature-badge"><img loading="lazy" src="/images/pages/about/6a7437a62d38f1d4f9679d87_security_1.svg" alt="Security Icon" class="story-feature-icon"></div><div class="story-feature-content"><div class="text-black">Quality parts and workmanship guaranteed</div></div></div></div></div></div><div scroll-item="" class="story-right"><img src="/images/pages/about/6a75bae84b1c4c011899c89a_about-Single-image.webp" loading="lazy" sizes="(max-width: 479px) 48vw, 49vw" srcset="/images/pages/about/6a75bae84b1c4c011899c89a_about-Single-image.webp 500w, /images/pages/about/6a75bae84b1c4c011899c89a_about-Single-image.webp 800w, /images/pages/about/6a75bae84b1c4c011899c89a_about-Single-image.webp 820w" alt="About Image" class="story-image"></div></div></div></section>`;

export default function AboutPageStorySection() {
  return <ScrapedSection html={SECTION_HTML} qa="about-02-story" />;
}
