// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section data-scroll="load" class="section-spacing-bottom"><div class="container"><div class="w-layout-grid grid-about"><div scroll-item="" class="about-left"><img src="/images/pages/about/6a75be698c131784ac3741c9_about-Single-image1.webp" loading="lazy" sizes="(max-width: 479px) 48vw, 49vw" srcset="/images/pages/about/6a75be698c131784ac3741c9_about-Single-image1.webp 500w, /images/pages/about/6a75be698c131784ac3741c9_about-Single-image1.webp 800w, /images/pages/about/6a75be698c131784ac3741c9_about-Single-image1.webp 820w" alt="About Image" class="about-image"></div><div class="about-right"><div class="about-content"><h2 scroll-item="" class="no-margin-bottom">Real people behind every repair.</h2><p scroll-item="" class="no-margin-bottom">As we've grown, our values haven't changed. We believe vehicle repairs should be straightforward, transparent, and stress-free. That's why we keep you informed at every stage and only carry out work you've approved.</p></div><div scroll-item="" class="about-feature-list"><div class="list-item"><div class="list-icon-wrap"><img loading="lazy" src="/images/pages/about/6a75710eaad25c81aca869a1_check-list-icon.svg" alt="Check Icon" class="list-icon"></div><div class="list-title w-variant-82b56992-5294-3eef-c465-a7178ad9b7df">Friendly, experienced technicians</div></div><div class="list-item"><div class="list-icon-wrap"><img loading="lazy" src="/images/pages/about/6a75710eaad25c81aca869a1_check-list-icon.svg" alt="Check Icon" class="list-icon"></div><div class="list-title w-variant-82b56992-5294-3eef-c465-a7178ad9b7df">Clear communication from start to finish</div></div><div class="list-item"><div class="list-icon-wrap"><img loading="lazy" src="/images/pages/about/6a75710eaad25c81aca869a1_check-list-icon.svg" alt="Check Icon" class="list-icon"></div><div class="list-title w-variant-82b56992-5294-3eef-c465-a7178ad9b7df">Trusted by local drivers year after year</div></div></div></div></div></div></section>`;

export default function AboutPagePeopleSection() {
  return <ScrapedSection html={SECTION_HTML} qa="about-03-people" />;
}
