/** Auto-generated by scripts/prepare-motocare-assets.mjs — do not edit manually */
export const ASSETS = {
  "asset-0": "/images/brand/logo.svg",
  "asset-1": "/images/hero/hero.webp",
  "asset-2": "/images/ui/ticker-sep.svg",
  "asset-3": "/images/services/service-01.webp",
  "asset-4": "/images/icons/service-01.svg",
  "asset-5": "/images/services/service-02.webp",
  "asset-6": "/images/icons/service-02.svg",
  "asset-7": "/images/services/service-03.webp",
  "asset-8": "/images/icons/service-03.svg",
  "asset-9": "/images/services/service-04.webp",
  "asset-10": "/images/icons/service-04.svg",
  "asset-11": "/images/about/single-image.webp",
  "asset-12": "/images/testimonials/avatar-1.png",
  "asset-13": "/images/testimonials/avatar-2.png",
  "asset-14": "/images/testimonials/avatar-3.png",
  "asset-15": "/images/icons/call.svg",
  "asset-16": "/images/icons/tag.svg",
  "asset-17": "/images/icons/calendar.svg",
  "asset-18": "/images/icons/security.svg",
  "asset-19": "/images/clients/client-01.svg",
  "asset-20": "/images/clients/client-11.svg",
  "asset-21": "/images/clients/client-03.svg",
  "asset-22": "/images/clients/client-04.svg",
  "asset-23": "/images/clients/client-05.svg",
  "asset-24": "/images/clients/client-10.svg",
  "asset-25": "/images/clients/client-07.svg",
  "asset-26": "/images/clients/client-08.svg",
  "asset-27": "/images/clients/client-09.svg",
  "asset-28": "/images/hero/hero-dashboard.webp",
  "asset-29": "/images/icons/star.svg",
  "asset-30": "/images/reviews/avatar-4.avif",
  "asset-31": "/images/reviews/avatar-5.avif",
  "asset-32": "/images/reviews/avatar-6.avif",
  "asset-33": "/images/team/technician.webp",
  "asset-34": "/images/ui/quote.svg",
  "asset-35": "/images/team/team-02.webp",
  "asset-36": "/images/team/team-01.webp",
  "asset-37": "/images/team/team-03.webp",
  "asset-38": "/images/team/team-04.webp",
  "asset-39": "/images/guarantee/guarantee-bg.webp",
  "asset-40": "/images/icons/check-list.svg",
  "asset-41": "/images/contact/footer-cta-bg.webp",
  "asset-42": "/images/brand/logo-footer.svg",
  "asset-43": "/images/icons/facebook.svg",
  "asset-44": "/images/icons/twitter.svg",
  "asset-45": "/images/icons/instagram.svg",
  "asset-47": "/images/ui/shape.svg",
  "asset-48": "/images/ui/decorative-01.svg",
  "asset-58": "/images/ui/checkbox.svg",
  "asset-59": "/images/icons/back-arrow.svg",
  "asset-60": "/images/icons/check-white.svg"
} as const;

export const BRAND = {
  logo: "/brand/vonos-autos-logo.png",
  logoFooter: "/brand/vonos-autos-logo.png",
} as const;

export const HERO_IMAGES = [ASSETS["asset-1"], ASSETS["asset-28"]] as const;

export const SERVICE_IMAGES = [
  ASSETS["asset-3"],
  ASSETS["asset-5"],
  ASSETS["asset-7"],
  ASSETS["asset-9"],
] as const;

export const SERVICE_ICONS = [
  ASSETS["asset-4"],
  ASSETS["asset-6"],
  ASSETS["asset-8"],
  ASSETS["asset-10"],
] as const;

export const CLIENT_LOGOS = [
  ASSETS["asset-19"],
  ASSETS["asset-21"],
  ASSETS["asset-22"],
  ASSETS["asset-23"],
  ASSETS["asset-25"],
  ASSETS["asset-26"],
  ASSETS["asset-27"],
  ASSETS["asset-24"],
  ASSETS["asset-20"],
] as const;

export const TEAM_IMAGES = [
  ASSETS["asset-36"],
  ASSETS["asset-35"],
  ASSETS["asset-37"],
  ASSETS["asset-38"],
] as const;

export const REVIEW_AVATARS = [
  ASSETS["asset-30"],
  ASSETS["asset-31"],
  ASSETS["asset-32"],
] as const;

export const GUARANTEE_BG = ASSETS["asset-39"];
export const FOOTER_CTA_BG = ASSETS["asset-41"];
