// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section id="home" class="none"><div class="container-full"><div class="hero-detail"><div class="hero-content"><div class="hero-left"><div data-show=""><div class="pre-title">Independent auto workshop — Est. 2009</div></div><h1 data-show="" class="text-white no-margin-bottom">Honest repairs. Every make</h1></div><div data-show="" class="hero-right"><div class="hero-contact-info w-form"><h2 class="heading-h5 no-margin-bottom">Reserve your service appointment</h2><form id="Contact-Form" name="wf-form-Contact-Form" method="get" class="hero-contact-form" aria-label="Contact Form"><div class="label"><label for="name" class="field-title">Full name*</label><input class="form-input no-margin-bottom w-input" maxlength="256" name="name" placeholder="Enter your full name" type="text" id="name" required=""></div><div class="label"><label for="email" class="field-title">Email address*</label><input class="form-input no-margin-bottom w-input" maxlength="256" name="email" placeholder="info@vonos.com" type="email" id="email" required=""></div><div class="label"><label for="Phone-Number" class="field-title">Phone number*</label><input class="form-input no-margin-bottom w-input" maxlength="256" name="Phone-Number" placeholder="Your phone number" type="tel" id="Phone-Number" required=""></div><div class="label"><label for="Location" class="field-title">Location</label><select id="Location" name="Location" class="form-select contact-select w-select"><option value="Select…">Select…</option><option value="Servicing &amp; MOT">Servicing &amp; MOT</option><option value="Brakes &amp; Suspension">Brakes &amp; Suspension</option><option value="Tires &amp; Alignment">Tires &amp; Alignment</option><option value="Diagnostics &amp; Electrical">Diagnostics &amp; Electrical</option></select></div><input type="submit" class="button-primary contact-button w-button" value="Book appointment"></form><div class="success-message w-form-done" role="region" aria-label="Contact Form success"><div>Your form has been submitted successfully. Thank you!</div></div><div class="error-message w-form-fail" role="region" aria-label="Contact Form failure"><div>Please double-check your information and try again. If the issue continues, you can also email us directly at info@yourdomain.com</div></div></div></div></div><div class="hero-bg-item"><img class="hero-bg-image" src="/images/hero/hero.webp" alt="BG Image" sizes="(max-width: 1920px) 100vw, 1920px" fetchpriority="high" srcset="/images/hero/hero.webp 500w, /images/hero/hero.webp 800w, /images/hero/hero.webp 1080w, /images/hero/hero.webp 1600w, /images/hero/hero.webp 1920w"><div class="hero-bg-overlay"></div><div class="hero-bg-overlay _02"></div></div></div></div></section>`;

export default function HeroSection() {
  return <ScrapedSection html={SECTION_HTML} qa="01-hero" />;
}
