// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section data-scroll="load" class="section-spacing-bottom"><div class="container"><div class="section-title"><div class="testimonial-header"><div scroll-item="" class="testimonial-left"><div class="pre-title w-variant-7e8276b8-3fa3-b83e-411c-2eeab6ce4110">User feedback</div><h2 class="no-margin-bottom">Trusted by people who hate being ripped off.</h2></div><div scroll-item="" class="testimonial-right"><h2 class="no-margin-bottom">4.9</h2><img src="/images/icons/star.svg" loading="lazy" alt="Star Icon" class="testimonial-review-icon"><div class="text-sm">412 verified Google reviews</div></div></div></div><div class="w-layout-grid grid-testimonial-list"><div scroll-item="" class="testimonial-card"><div class="testimonial-rating-info"><img loading="lazy" src="/images/icons/star.svg" alt="Star Icon" class="testimonial-rating-icon"><p class="testimonial-review">Quoted a fair fixed price, and that’s exactly what I paid when I collected. First garage I’ve actually trusted.</p></div><div class="testimonial-client-info"><div class="testimonial-avatar-item"><img loading="lazy" src="/images/reviews/avatar-4.avif" alt="Avatar " class="testimonial-avatar"></div><div class="testimonial-client-content"><div class="testimonial-client-name">Caroline Wells</div><div class="text-sm">VW Golf GTI</div></div></div></div><div scroll-item="" class="testimonial-card"><div class="testimonial-rating-info"><img loading="lazy" src="/images/icons/star.svg" alt="Star Icon" class="testimonial-rating-icon"><p class="testimonial-review">Found an electrical fault two other places missed. Diagnosed and back on the road the same day.</p></div><div class="testimonial-client-info"><div class="testimonial-avatar-item"><img loading="lazy" src="/images/reviews/avatar-5.avif" alt="Avatar " class="testimonial-avatar"></div><div class="testimonial-client-content"><div class="testimonial-client-name">Sofia Conti</div><div class="text-sm">BMW 3 Series</div></div></div></div><div><div scroll-item="" class="testimonial-card"><div class="testimonial-rating-info"><img loading="lazy" src="/images/icons/star.svg" alt="Star Icon" class="testimonial-rating-icon"><p class="testimonial-review">Booked online, dropped the keys, sorted. They explained everything in plain English - no jargon, no pressure.</p></div><div class="testimonial-client-info"><div class="testimonial-avatar-item"><img loading="lazy" src="/images/reviews/avatar-6.avif" alt="Avatar " class="testimonial-avatar"></div><div class="testimonial-client-content"><div class="testimonial-client-name">Lukas Schneider</div><div class="text-sm">Nissan Qashqai</div></div></div></div></div></div></div></section>`;

export default function ReviewsSection() {
  return <ScrapedSection html={SECTION_HTML} qa="08-reviews" />;
}
