// AUTO-GENERATED from standalone scrape — do not edit by hand
// Regenerate: npm run prepare:subpages

import ScrapedSection from "@/components/marketing/ScrapedSection";

const SECTION_HTML = `<section data-scroll="load" class="section-spacing-bottom"><div class="container"><div scroll-item="" class="section-title text-center"><div class="pre-title w-variant-7e8276b8-3fa3-b83e-411c-2eeab6ce4110">Meet the Technician Before the Repair Begins</div></div><div class="technician-content"><div scroll-item="" class="w-layout-grid grid-technician-list"><div class="technician-left"><img src="/images/team/technician.webp" loading="lazy" sizes="(max-width: 479px) 100vw, 49vw" srcset="/images/team/technician.webp 500w, /images/team/technician.webp 800w" alt="BG Image" class="testimonial-image"><div class="technician-info"><h2 class="technician-name">Dan Whitlock</h2><div class="text-sm text-white-op70">Founder &amp; MOT tester · 17 yrs</div></div></div><div class="technician-right"><img src="/images/ui/quote.svg" loading="lazy" alt="Quote Icon" class="technician-icon"><h3 class="technician-review">I started Vonos because I was sick of watching mates get overcharged. We inspect first, confirm pricing on diagnosis, and only start work once you approve the quote.</h3><a href="/contact" class="button-primary w-inline-block"><div class="button-title">Book your car in</div><div class="button-hover-bg"></div></a></div></div><div class="w-layout-grid grid-team-list"><div scroll-item="" class="team-item"><img loading="lazy" src="/images/team/team-02.webp" alt="Team Image" class="team-avatar"><div class="team-detail"><h3 class="team-name">Marcus Hill</h3><div class="team-job-position">Senior technician · 12 yrs</div></div></div><div scroll-item="" class="team-item"><img loading="lazy" src="/images/team/team-01.webp" alt="Team Image" class="team-avatar"><div class="team-detail"><h3 class="team-name">Sofia Reyes</h3><div class="team-job-position">Diagnostics lead · 9 yrs</div></div></div><div scroll-item="" class="team-item"><img loading="lazy" src="/images/team/team-03.webp" alt="Team Image" class="team-avatar"><div class="team-detail"><h3 class="team-name">Priya Anand</h3><div class="team-job-position">Service advisor · 6 yrs</div></div></div><div class="team-item-wrap"><div scroll-item="" class="team-item"><img loading="lazy" src="/images/team/team-04.webp" alt="Team Image" class="team-avatar"><div class="team-detail"><h3 class="team-name">Tom Beckett</h3><div class="team-job-position">Tire tech · 5 yrs</div></div></div></div></div></div></div></section>`;

export default function TeamSection() {
  return <ScrapedSection html={SECTION_HTML} qa="09-team" />;
}
